bad = {...
	'daisy5_20190404', 'TetrodeRecording', 'Undefined function ''abs'' for input arguments of type ''cell''.';...
	'daisy5_20190411', 'TetrodeRecording', 'Undefined function ''abs'' for input arguments of type ''cell''.';...
	'daisy5_20190423', 'TetrodeRecording', 'Undefined function ''abs'' for input arguments of type ''cell''.';...
	'daisy5_20190424', 'TetrodeRecording', 'Undefined function ''abs'' for input arguments of type ''cell''.';...
	'desmond12_20190329', 'TetrodeRecording', 'Undefined function ''abs'' for input arguments of type ''cell''.';...
	'desmond12_20190401', 'TetrodeRecording', 'Undefined function ''abs'' for input arguments of type ''cell''.';...
	'desmond12_20190402', 'TetrodeRecording', 'Undefined function ''abs'' for input arguments of type ''cell''.';...
	'desmond12_20190403', 'TetrodeRecording', 'Undefined function ''abs'' for input arguments of type ''cell''.';...
	'desmond12_20190405', 'TetrodeRecording', 'Undefined function ''abs'' for input arguments of type ''cell''.';...
	'desmond12_20190410', 'TetrodeRecording', 'Undefined function ''abs'' for input arguments of type ''cell''.';...
	'desmond12_20190411', 'TetrodeRecording', 'Undefined function ''abs'' for input arguments of type ''cell''.';...
	'desmond12_20190416', 'TetrodeRecording', 'Undefined function ''abs'' for input arguments of type ''cell''.';...
	'desmond12_20190417', 'TetrodeRecording', 'Undefined function ''abs'' for input arguments of type ''cell''.';...
	'desmond12_20190422', 'TetrodeRecording', 'Undefined function ''abs'' for input arguments of type ''cell''.';...
	'desmond12_20190423', 'TetrodeRecording', 'Undefined function ''abs'' for input arguments of type ''cell''.';...
	'desmond13_20190404', 'TetrodeRecording', 'Undefined function ''abs'' for input arguments of type ''cell''.';...
	'desmond13_20190408', 'TetrodeRecording', 'Undefined function ''abs'' for input arguments of type ''cell''.';...
	'desmond13_20190409', 'TetrodeRecording', 'Undefined function ''abs'' for input arguments of type ''cell''.';...
	'desmond13_20190424', 'TetrodeRecording', 'Undefined function ''abs'' for input arguments of type ''cell''.';...
};