tr = TetrodeRecording();

% Select files
tr.SelectFiles();

% This reads the files and then tr.SpikeDetect()
tr.ReadFiles('ChunkSize',10,...
    'NumSigmas', 2.5,...
    'NumSigmasReturn', 1.25,...
    'NumSigmasReject', 40,...
    'WaveformWindow', [-0.5, 0.5]);

% This automatically PCA's and clusters into 3 groups, This calls tr.FeatureExtract(), i.e., PCA, then tr.Cluster(), i.e. kmeans
tr.SpikeSort([],...
    'FeatureMethod', 'PCA',...
    'Dimension', 3,...
    'ClusterMethod', 'kmeans')

% Plot waveforms all channels
tr.PlotAllChannels('plotMethod', 'mean');
%% read in spikesorter data. you need to specify the files before this

% optional: read in all the files...
tr.SelectFiles();

units = import_spikes('/Users/lilis/Dropbox (MIT)/1 ASSAD LAB/testFiles/Ephys Test/sorted_data_ssc_4_11_2023.csv', false) % /Users/lilis/Dropbox (MIT)/1 ASSAD LAB/testFiles/Ephys Test/sorted_data.csv', false);
%
tr.ReadFiles('ChunkSize',10,...
    'SpikeSorterAlign',true,...
    'SpikeSorterCSV',units,...
    'WaveformWindow', [-2, 2]);

%% Spike Sort Manually with LFH's GUI
% The first argument is channel index. Or leave empty to plot channel 1.
tr.PlotChannel(8, 'Reference','StartCuOn',...
    'Event', 'JuiceOn',...
    'Exclude', '',...
    'Event2', '',...
    'Exclude2', '',...
    'RasterXLim', [-8, 1],...
    'ExtendedWindow', [-1, 1],...
    'WaveformYLim', [-50, 50],...
    'PlotStim', false);

%% find all clusters from SS on same channel. Then examine each in turn...